### ISSUE TITLE
[Question] regarding the min-api 21

### ISSUE THREAD

**Issue by anuchandy** [retrostreams/android-cfuture21-hack#1]
thank you for writing this library. I've a question, the readme says:

> ... attempt to provide CompletableFuture on Android API level 21 to level 23 in conjunction with google/desugar_jdk_libs and Android Gradle Plugin 4.x

Could you share more details about the min level 21? From my experience, google's desugar_jdk_libs can desugar below 21, is there any platform APIs this library uses that is not available below L21 and cannot be desugared?

**Comment by stefan-zobel** [comment]
I'm not quite sure anymore why I said L21. The original implementation was based on the code from android-retrostreams which needs _j.u.c.RecursiveTask_ (introduced in L21 and afaik not available in desugar_jdk_libs). But that dependency doesn't exist anymore. In any case, I've only tested this on API level >= 21.

**Comment by anuchandy** [comment]
Thanks for the answer @stefan-zobel.
